version: '3'

services:
 bdd:
  image: postgres
  environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=postgresql_bdd
  ports:
    - "5000:5000"
  networks:
    - bridge
 app:
  build: .
  image: necene12/image_api_bdd_postgresql
  ports:
    - "8000:8000"
  depends_on:
    - bdd
  volumes:
    - ../data
  networks:
    - bridge

networks:
  bridge:
